Fixed build failure when compiling with clang++
src/LuaPlus/LuaPlusCD.h:1045:61: error: cast from pointer to smaller type 'unsigned int' loses information
            LPCD::Push(L, *(VarType*)((unsigned char*)obj + (unsigned int)offset));
                                                            ^~~~~~~~~~~~~~~~~~~~
src/LuaPlus/LuaPlusCD.h:1059:47: error: cast from pointer to smaller type 'unsigned int' loses information
            *(VarType*)((unsigned char*)obj + (unsigned int)offset) = LPCD::Get(LPCD::TypeWrapper<VarType>(), L, 2);
                                              ^~~~~~~~~~~~~~~~~~~~

Even Microsoft supports 'stdint.h' in the latest versions of their
compiler nowadays, so it's time to use it safely.

From: Siarhei Siamashka <siarhei.siamashka@gmail.com>